# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
ignore:
  - **/tk_*.py
  - custom_step/colourchooser.py
  - custom_step/findwindow.py
  - custom_step/fontchooser.py
  - custom_step/highlighter.py
  - custom_step/linenumbers.py
  - custom_step/textarea.py
  - custom_step/texteditor.py
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
