language: python
script: pytest
os: linux

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
    # Activate the test environment
  - conda activate test
    # Build and install package
    #- python setup.py develop --no-deps
  - pip install -e .
    # Print details of the environment
  - conda list
  - pip freeze

notifications:
    email: false

stages:
  - lint
  - test
  - deploy

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: "Check formatting of code for PEP-8"
      os: linux
      language: generic
      env: PYTHON_VER=3.7
      script:
        - flake8 custom_step tests
        - yapf --diff --recursive  custom_step tests

    - stage: test
      name: "Tests on MacOS Python 3.6"
      script:
        - pytest -v tests/
      os: osx
      language: generic
      env: PYTHON_VER=3.6

    - stage: test
      name: "Tests on MacOS Python 3.7"
      script:
        - pytest -v tests/
      os: osx
      language: generic
      env: PYTHON_VER=3.7

    - stage: test
      name: "Tests on Linux Python 3.6"
      script:
        - pytest -v tests/
      os: linux
      language: generic  # No need to set Python version since its conda
      env: PYTHON_VER=3.6

    - stage: test
      name: "Tests and coverage on Linux Python 3.7"
      script:
        - pytest -v --cov=custom_step tests/
      after_success:
        - codecov
      os: linux
      language: generic
      env: PYTHON_VER=3.7

    - stage: deploy
      name: "Deploy to PyPi"
      if: tag IS present
      os: linux
      dist: xenial
      python: 3.7
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        skip_existing: true
        on:
          condition: $PYTHON_VER = 3.7
          condition: $TRAVIS_OS_NAME = linux
          repo: molssi-seamm/custom_step
          tags: true
        username: seamm
        password:
          secure: qQxmOlaEkS2Ea2WWN/7mGG2idFF4FEFTKV9/ELI/b5IK4dUzIcDbXWuJ5+T1gCMv2yTpeLY3AmLEoXzSxwZTq/7TmK2YNmYyBTEl24PXNo2vEp/NHGjEyu+cLaw46W8A/BwU+CLciTvka2yNGOknTCV4hzdBGNd6vt0ooL9U23JpV7jdjQVp2WEry7EBdwPYrYj6AxyyzE3XvkqUAyCVKCH916MjKgCWXCdMK95OGENWXp2jFTjqBrSddwjFfg0IaJLHghQhi7WAQipLmZU1Y1vgjEhjIh/VSqlzBRg8Vl0G570daOI3YR3WWL2HBTGmMxQjHwoXMFcfjvcL7ish38p6+Wx7SztfA46rwnj+CEwevgpSzim9Mv5A8QcbKEVmdxjr+wVIcPt/MqZ/mUu43/Vt+x4Z+PdqSLqqiUhdk+6C6zN8GTw6QYx4yJy0a1XTl+jvkzIsB/jrWJWvzSB9AMgZ95j1WjeM0E2h6pd3rYoESN6lO69NqqEyHzo57zqWil74A+obF64veBgZqMy6YCgHkrqiqmHEp7kln+myOv7Z35z3qmNsJYb/rTw7PktjxHUR3HRNrU/t/4JGzaV79KN3Br1F5m1kXRdGvpIfSOYCxFbvF2ElcXTuoXyYmTtF5VgURX1P5YT3ZXttJLcE5L6HJ+NCEV9oMeDOb1Uy+z8=
